#!/bin/bash
echo "enter the 3 numbers"
read n1 n2 n3
if [ $n1 -gt $n2 ] ; then
if [ $n1 -gt $n3 ] ; then
echo -e "$n1 is the greatest number"
else
echo -e "$n3 is the greatest number"
fi
else
if [ $n2 -gt $n3 ] ; then
echo -e "$n2 is the greatest number"
else
echo -e "$n3 is the greatest number"
fi
fi
